services:
  fastapi_app:
    build: .
    container_name: vigyaan-container-green
    image: vigyaan-image
    restart: always
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3