services:
  fastapi_app:
    build: .
    container_name: vigyaan-container-green
    image: vigyaan-image
    restart: always
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - .:/app