services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: apikeys_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    build: .
    container_name: vigyaan-container
    image: vigyaan-image
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@postgres/apikeys_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: