name: Keep App Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping application
        run: |
          APP_URL="https://vigyaan.onrender.com"
          echo "Pinging ${APP_URL}"
          CODE=$(curl -s -o /dev/null -w "%{http_code}" "${APP_URL}" || true)
          echo "HTTP status: $CODE"
          if [ "$CODE" -ge 500 ]; then
            echo "Server error" >&2
            exit 1
          fi
